### ISSUE TITLE
Job posting functionality 

### ISSUE THREAD

**Issue by mistersuun** [Irisvella/DreamTeam-SOEN-341-Project-2023#16]
Setting up the page were the postings. Generic html base (Login not required to see postings)

**Comment by Irisvella** [comment]
As a user, I want to be able to see and post job offering because this is the main functionality of this website. 
As an employer, I want to be able to post and edit job offerings.
As a job seeker, I want to be able to look at job offerings and apply. 

Tasks: 
- Create a page that lists job offerings. 
- Create a job posting and editing system for employers
